// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AtmIconSvg: typeof import('./src/components/icons/atm-icon-svg.vue')['default']
    CardList: typeof import('./src/components/partials/CardList.vue')['default']
    CreditCardIconSvg: typeof import('./src/components/icons/credit-card-icon-svg.vue')['default']
    EmptyCardList: typeof import('./src/components/partials/EmptyCardList.vue')['default']
    EmptyCreditCardSvg: typeof import('./src/components/icons/empty-credit-card-svg.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MastercardCardIconSvg: typeof import('./src/components/icons/mastercard-card-icon-svg.vue')['default']
    MobilePhoneIconSvg: typeof import('./src/components/icons/mobile-phone-icon-svg.vue')['default']
    Navbar: typeof import('./src/components/nav/Navbar.vue')['default']
    NavbarCard: typeof import('./src/components/nav/NavbarCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VisaCardIconSvg: typeof import('./src/components/icons/visa-card-icon-svg.vue')['default']
    WalletIconSvg: typeof import('./src/components/icons/wallet-icon-svg.vue')['default']
  }
}

export {}
